### ISSUE TITLE
Debugging failes with: esp32: Faied to read insn (-4)!

### ISSUE THREAD

**Issue by olivierzign** [espressif/openocd-esp32#57]
I've got a problem debugging the ESP32 via OpenOCD.
When I start debugging I get the following error:
`Error: 6098 918708 esp32.c:982 esp32_add_sw_breakpoint(): esp32: Faied to read insn (-4)!
Error: 6099 918708 esp32.c:1017 xtensa_add_breakpoint(): esp32: Faied to add SW BP!
Error: 6100 918708 breakpoints.c:94 breakpoint_add_internal(): can't add breakpoint: resource not available
`
I've tested it via Eclipse and in the gdb command line but got same result. 
The hardware setup also seems ok as I've been able to debug with this setup in the past.

Does anyone have an idea where I need to look? (I've attached the openocd and dgb logs.)

Tnx!

JTAG debugger: Olimex ARM-USB-TINY-H
OS: Windows 10 (native)

[openocd_log.txt](https://github.com/espressif/openocd-esp32/files/2324445/openocd_log.txt)
[gdb_log.txt](https://github.com/espressif/openocd-esp32/files/2324450/gdb_log.txt)

**Comment by olivierzign** [comment]
Just found out that it is a bug in openocd version i'm using (v0.10.0-esp32-20180724)
The command "gdb_breakpoint_override hard"  was removed from 
/openocd/scripts/target/esp32.cfg 

Re-adding it to  line 100 fixed the issue.
Should already be fixed in repo. 
(https://community.platformio.org/t/esp32-pio-unified-debugger/4541/22)

**Comment by kolipakakondal** [comment]
It's fixed with https://github.com/espressif/openocd-esp32/releases/tag/v0.10.0-esp32-20190708

**Comment by sebastianbasierski** [comment]
Hi, i'm using the latest version of openocd and i still see this error.
[esp32.log](https://github.com/espressif/openocd-esp32/files/3428517/esp32.log)

**Comment by manuelbl** [comment]
@sebastianbasierski The output looks similar to an output I had a few days ago. The problem wasn't the debugger but rather my software. I accidentally typed 6 as a GPIO number (instead of 16 where the peripheral was connected to). GPIO 6 is used to access flash memory. So the problem was that the debugger couldn't access the flash memory.

You might want to check that you are not using GPIO 6 through GPIO 11.
